# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newtable.ui'
#
# Created: Wed Apr  6 17:09:11 2011
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_NewTable(object):
    def setupUi(self, NewTable):
        NewTable.setObjectName("NewTable")
        NewTable.resize(393, 552)
        self.verticalLayout_4 = QtGui.QVBoxLayout(NewTable)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtGui.QLabel(NewTable)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.name = QtGui.QLineEdit(NewTable)
        self.name.setObjectName("name")
        self.horizontalLayout_4.addWidget(self.name)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.groupBox = QtGui.QGroupBox(NewTable)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.geocol = QtGui.QCheckBox(self.groupBox)
        self.geocol.setObjectName("geocol")
        self.verticalLayout.addWidget(self.geocol)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.geoname = QtGui.QLineEdit(self.groupBox)
        self.geoname.setMinimumSize(QtCore.QSize(130, 0))
        self.geoname.setObjectName("geoname")
        self.horizontalLayout_3.addWidget(self.geoname)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.geotype = QtGui.QComboBox(self.groupBox)
        self.geotype.setObjectName("geotype")
        self.horizontalLayout_3.addWidget(self.geotype)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.geosrid = QtGui.QLineEdit(self.groupBox)
        self.geosrid.setObjectName("geosrid")
        self.horizontalLayout.addWidget(self.geosrid)
        self.browseSRID = QtGui.QToolButton(self.groupBox)
        self.browseSRID.setObjectName("browseSRID")
        self.horizontalLayout.addWidget(self.browseSRID)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.dims = QtGui.QComboBox(self.groupBox)
        self.dims.setObjectName("dims")
        self.horizontalLayout.addWidget(self.dims)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.pkey = QtGui.QCheckBox(NewTable)
        self.pkey.setObjectName("pkey")
        self.verticalLayout_4.addWidget(self.pkey)
        self.groupBox_2 = QtGui.QGroupBox(NewTable)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.colname = QtGui.QLineEdit(self.groupBox_2)
        self.colname.setObjectName("colname")
        self.horizontalLayout_5.addWidget(self.colname)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.coltype = QtGui.QComboBox(self.groupBox_2)
        self.coltype.setObjectName("coltype")
        self.horizontalLayout_6.addWidget(self.coltype)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.add = QtGui.QPushButton(self.groupBox_2)
        self.add.setObjectName("add")
        self.horizontalLayout_2.addWidget(self.add)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(NewTable)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.columns = QtGui.QListView(self.groupBox_3)
        self.columns.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.columns.setObjectName("columns")
        self.verticalLayout_3.addWidget(self.columns)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem8)
        self.remove = QtGui.QPushButton(self.groupBox_3)
        self.remove.setObjectName("remove")
        self.horizontalLayout_7.addWidget(self.remove)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        self.buttonBox = QtGui.QDialogButtonBox(NewTable)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_4.addWidget(self.buttonBox)

        self.retranslateUi(NewTable)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), NewTable.reject)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), NewTable.accept)
        QtCore.QMetaObject.connectSlotsByName(NewTable)

    def retranslateUi(self, NewTable):
        NewTable.setWindowTitle(QtGui.QApplication.translate("NewTable", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("NewTable", "New Table Name", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("NewTable", "Geometry Column", None, QtGui.QApplication.UnicodeUTF8))
        self.geocol.setText(QtGui.QApplication.translate("NewTable", "Geometry Column", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("NewTable", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("NewTable", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("NewTable", "SRID", None, QtGui.QApplication.UnicodeUTF8))
        self.browseSRID.setText(QtGui.QApplication.translate("NewTable", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("NewTable", "Dim", None, QtGui.QApplication.UnicodeUTF8))
        self.pkey.setText(QtGui.QApplication.translate("NewTable", "Create autoincrement Primary key", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("NewTable", "New Column", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("NewTable", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("NewTable", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.add.setText(QtGui.QApplication.translate("NewTable", "Add New Column", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("NewTable", "Columns", None, QtGui.QApplication.UnicodeUTF8))
        self.remove.setText(QtGui.QApplication.translate("NewTable", "Remove Selected Column", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    NewTable = QtGui.QDialog()
    ui = Ui_NewTable()
    ui.setupUi(NewTable)
    NewTable.show()
    sys.exit(app.exec_())

